'''
This code was generated by GPT-3 in response to the following query:
 % python3 gptapi.py
Enter a prompt: How would you create a simple BankAccount class in Python to deposit and withdraw funds and get the balance?
'''

class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        return self.balance

    def withdraw(self, amount):
        self.balance -= amount
        return self.balance

    def get_balance(self):
        return self.balance

# Usage:

account = BankAccount(100)
account.deposit(50)
account.withdraw(25)
print(account.get_balance()) # 125