// pages/index.js
  
import Head from 'next/head'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>CS103a NextJS Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Our First NextJS Demo!</h1>
        <Link href="/test">Visit the test page</Link>
      </main>
    </>
  )
}